"""
calculate_catchment_births.py
------------------------------
Allocates live birth counts (ONS 2016-2018, Table 4 of birthsbypcdfinal.xlsx)
to each hospital's catchment using proportional sector splitting.

Method
------
Birth data is published at postcode-sector level (e.g. "SW1A 1").
Full postcodes (e.g. "SW1A 1AA") are assigned to hospitals via output/analysis/All_Postcodes.csv.
A single sector often spans multiple hospital catchments, so births are split
proportionally by the share of full postcodes in each sector that belong to
each hospital.

  hospital_births(sector) = sector_births × (hospital_postcodes_in_sector
                                              / total_postcodes_in_sector)

This is a standard areal interpolation approach (postcode-count weighting).
It assumes uniform birth density within a sector — a reasonable approximation
given the fine granularity of postcode sectors.

Inputs
------
  birthsbypcdfinal.xlsx     — ONS live births by postcode sector, Table 4
                              (2016-2018 combined). Cols: Postcode, LA code,
                              LA name, Total births, …
    output/analysis/All_Postcodes.csv  — Generated by postcode_lookup.py --profile analysis.

Outputs
-------
  output/Hospital_Catchment_Births.csv
  docs/births.json           — for the static visualisation page
"""

import csv
import json
import os
import re
from collections import defaultdict

import openpyxl

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
BIRTHS_XLSX   = os.path.join(BASE_DIR, "birthsbypcdfinal.xlsx")
ALL_POSTCODES = os.path.join(BASE_DIR, "output", "analysis", "All_Postcodes.csv")
OUTPUT_CSV    = os.path.join(BASE_DIR, "output", "Hospital_Catchment_Births.csv")
OUTPUT_JSON   = os.path.join(BASE_DIR, "docs", "births.json")


def normalise_postcode(pc: str) -> str:
    """Canonical spaced UK postcode: 'TW196BP' → 'TW19 6BP'."""
    pc = re.sub(r"\s+", "", pc).upper()
    return (pc[:-3] + " " + pc[-3:]) if len(pc) >= 5 else pc


def postcode_to_sector(pc: str) -> str:
    """'SW1A 1AA' → 'SW1A 1'  (outward + first inward digit)."""
    pc = normalise_postcode(pc)
    parts = pc.split(" ")
    if len(parts) == 2:
        return parts[0] + " " + parts[1][0]
    return pc


# ── Step 1: Load sector births from Table 4 ───────────────────────────────────
print("Loading birth data from Table 4 (2016-2018) …")

sector_births: dict[str, float] = {}

wb = openpyxl.load_workbook(BIRTHS_XLSX, read_only=True)
ws = wb["Table 4"]
header_found = False

for row in ws.iter_rows(values_only=True):
    # Header row starts with 'Postcode'
    if not header_found:
        if row[0] == "Postcode":
            header_found = True
        continue
    sector = row[0]
    total  = row[3]
    if sector is None or total is None:
        continue
    # Normalise sector spacing: remove extra spaces, ensure single space
    sector = re.sub(r"\s+", " ", str(sector).strip()).upper()
    try:
        sector_births[sector] = float(total)
    except (TypeError, ValueError):
        pass

wb.close()
print(f"  Loaded {len(sector_births):,} postcode sectors with birth counts.")

# ── Step 2: Build sector → hospital counts from output/analysis/All_Postcodes.csv
print("Building sector → catchment mapping from output/analysis/All_Postcodes.csv …")

LEVEL_COLS = {
    "Any": "Closest_Any",
    "L1":  "Closest_L1",
    "L2":  "Closest_L2",
    "L3":  "Closest_L3",
}

# sector_hospital_counts[level][sector][hospital] = number of postcodes
sector_hospital_counts: dict[str, dict[str, dict[str, int]]] = {
    lvl: defaultdict(lambda: defaultdict(int)) for lvl in LEVEL_COLS
}

total_postcodes_in_sector: dict[str, int] = defaultdict(int)

with open(ALL_POSTCODES, newline="", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)
    for row in reader:
        pc     = normalise_postcode(row["Postcode"])
        sector = postcode_to_sector(pc)
        total_postcodes_in_sector[sector] += 1
        for lvl, col in LEVEL_COLS.items():
            hospital = row.get(col, "").strip()
            if hospital:
                sector_hospital_counts[lvl][sector][hospital] += 1

print(f"  Mapped {len(total_postcodes_in_sector):,} unique sectors from catchment data.")

# ── Step 3: Proportionally allocate births to hospitals ───────────────────────
print("Allocating births proportionally …")

# hospital_births[level][hospital] = allocated births (float, round at output)
hospital_births: dict[str, dict[str, float]] = {lvl: defaultdict(float) for lvl in LEVEL_COLS}

unmatched_sectors = 0
matched_sectors   = 0

for sector, births in sector_births.items():
    if sector not in total_postcodes_in_sector:
        unmatched_sectors += 1
        continue
    matched_sectors += 1
    total_pcs = total_postcodes_in_sector[sector]

    for lvl in LEVEL_COLS:
        hosp_counts = sector_hospital_counts[lvl].get(sector, {})
        if not hosp_counts:
            continue
        # Confirm denominator matches (should equal total_pcs for Any level)
        denom = sum(hosp_counts.values())
        for hospital, count in hosp_counts.items():
            hospital_births[lvl][hospital] += births * (count / denom)

print(f"  Matched {matched_sectors:,} sectors | {unmatched_sectors:,} sectors in births data not in catchment data (outside London area).")

# ── Step 4: Collect all hospitals and build output rows ───────────────────────
all_hospitals = sorted(
    set().union(*[set(hospital_births[lvl].keys()) for lvl in LEVEL_COLS])
)
print(f"  {len(all_hospitals)} hospitals with allocated births.")

rows_out = []
for hospital in all_hospitals:
    rows_out.append({
        "Hospital":      hospital,
        "Any_Births":    round(hospital_births["Any"].get(hospital, 0)),
        "L1_Births":     round(hospital_births["L1"].get(hospital, 0)),
        "L2_Births":     round(hospital_births["L2"].get(hospital, 0)),
        "L3_Births":     round(hospital_births["L3"].get(hospital, 0)),
    })

# ── Step 5: Write CSV ──────────────────────────────────────────────────────────
os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)

fieldnames = ["Hospital", "Any_Births", "L1_Births", "L2_Births", "L3_Births"]

with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows_out)

print(f"\nCSV written to: {OUTPUT_CSV}")

# ── Step 6: Write docs/births.json ────────────────────────────────────────────
json_rows = [
    {
        "hospital":   r["Hospital"],
        "any_births": r["Any_Births"],
        "l1_births":  r["L1_Births"],
        "l2_births":  r["L2_Births"],
        "l3_births":  r["L3_Births"],
    }
    for r in rows_out
]

with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(json_rows, f, separators=(",", ":"))

print(f"JSON written to: {OUTPUT_JSON}")

# ── Step 7: Console summary ───────────────────────────────────────────────────
print(f"\n{'Hospital':<45} {'Any':>8}  {'L1':>8}  {'L2':>8}  {'L3':>8}")
print("-" * 85)
for r in rows_out:
    print(
        f"{r['Hospital']:<45} "
        f"{r['Any_Births']:>8,}  "
        f"{r['L1_Births']:>8,}  "
        f"{r['L2_Births']:>8,}  "
        f"{r['L3_Births']:>8,}"
    )
