"""
calculate_catchment_populations.py
-----------------------------------
Joins each hospital's catchment postcodes with the ONS postcode-level population
data (pcd_p001.csv) to produce a "Total Population" figure for each hospital at
each care level (Any / L1 / L2 / L3).

Inputs
------
  pcd_p001.csv          — ONS Census postcode population file.
                          Columns: Postcode, Sex Code, Sex Label, Count
                          (Two rows per postcode: one Female, one Male)
  output/All_Postcodes.csv — Generated by postcode_lookup.py.
                          Columns: Postcode, …, Closest_Any, …, Closest_L1, …,
                                   Closest_L2, …, Closest_L3, …

Output
------
  output/Hospital_Catchment_Populations.csv
      Hospital, Any_Postcodes, Any_Population, Any_Matched_Postcodes,
      L1_Postcodes, L1_Population, L1_Matched_Postcodes,
      L2_Postcodes, L2_Population, L2_Matched_Postcodes,
      L3_Postcodes, L3_Population, L3_Matched_Postcodes

Usage
-----
  python3 calculate_catchment_populations.py
"""

import csv
import json
import os
import re
from collections import defaultdict


def normalise_postcode(pc: str) -> str:
    """Return a consistently-spaced UK postcode (e.g. 'TW196BP' → 'TW19 6BP').
    The inward code (district + check digit) is always 3 characters, so we
    split at len-3 and rejoin with a single space."""
    pc = re.sub(r"\s+", "", pc).upper()
    if len(pc) >= 5:
        return pc[:-3] + " " + pc[-3:]
    return pc

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR        = os.path.dirname(os.path.abspath(__file__))
PCD_POP_FILE    = os.path.join(BASE_DIR, "pcd_p001.csv")
ALL_POSTCODES   = os.path.join(BASE_DIR, "output", "All_Postcodes.csv")
OUTPUT_FILE     = os.path.join(BASE_DIR, "output", "Hospital_Catchment_Populations.csv")
OUTPUT_JSON     = os.path.join(BASE_DIR, "docs", "populations.json")

# ── Step 1: Build postcode → total population lookup from pcd_p001.csv ─────────
print("Loading population data from pcd_p001.csv …")

postcode_pop: dict[str, int] = defaultdict(int)

with open(PCD_POP_FILE, newline="", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)
    for row in reader:
        pc = normalise_postcode(row["Postcode"])
        try:
            count = int(row["Count"])
        except (ValueError, KeyError):
            count = 0
        postcode_pop[pc] += count  # sums Female + Male rows automatically

print(f"  Loaded population data for {len(postcode_pop):,} unique postcodes.")

# ── Step 2: Load catchment assignments from All_Postcodes.csv ──────────────────
print("Loading catchment data from All_Postcodes.csv …")

# Maps: level_label → hospital_name → set of postcodes
catchments: dict[str, dict[str, set[str]]] = {
    "Any": defaultdict(set),
    "L1":  defaultdict(set),
    "L2":  defaultdict(set),
    "L3":  defaultdict(set),
}

LEVEL_COLS = {
    "Any": "Closest_Any",
    "L1":  "Closest_L1",
    "L2":  "Closest_L2",
    "L3":  "Closest_L3",
}

with open(ALL_POSTCODES, newline="", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)
    for row in reader:
        pc = normalise_postcode(row["Postcode"])
        for level, col in LEVEL_COLS.items():
            hospital = row.get(col, "").strip()
            if hospital:
                catchments[level][hospital].add(pc)

# Collect all hospital names across all levels
all_hospitals = sorted(
    set().union(
        *[set(catchments[lvl].keys()) for lvl in LEVEL_COLS]
    )
)
print(f"  Found {len(all_hospitals)} unique hospitals across all levels.")

# ── Step 3: Calculate population for each hospital × level ─────────────────────
print("Calculating catchment populations …")

rows_out = []

for hospital in all_hospitals:
    row_out = {"Hospital": hospital}

    for level in ("Any", "L1", "L2", "L3"):
        postcodes = catchments[level].get(hospital, set())
        total_pop = 0
        matched   = 0

        for pc in postcodes:
            if pc in postcode_pop:
                total_pop += postcode_pop[pc]
                matched   += 1

        row_out[f"{level}_Postcodes"]         = len(postcodes)
        row_out[f"{level}_Population"]        = total_pop
        row_out[f"{level}_Matched_Postcodes"] = matched

    rows_out.append(row_out)

# ── Step 4: Write output ───────────────────────────────────────────────────────
fieldnames = [
    "Hospital",
    "Any_Population",
    "L1_Population",
    "L2_Population",
    "L3_Population",
]

os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(rows_out)

# ── Step 5: Write docs/populations.json for the static visualisation page ──────
json_rows = [
    {
        "hospital":       r["Hospital"],
        "any_population": r["Any_Population"],
        "l1_population":  r["L1_Population"],
        "l2_population":  r["L2_Population"],
        "l3_population":  r["L3_Population"],
    }
    for r in rows_out
]

with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(json_rows, f, separators=(",", ":"))

print(f"JSON written to:  {OUTPUT_JSON}")

print(f"\nDone! Results written to: {OUTPUT_FILE}")
print(f"\n{'Hospital':<45} {'Any Pop':>12}  {'L1 Pop':>12}  {'L2 Pop':>12}  {'L3 Pop':>12}")
print("-" * 97)
for r in rows_out:
    print(
        f"{r['Hospital']:<45} "
        f"{r['Any_Population']:>12,}  "
        f"{r['L1_Population']:>12,}  "
        f"{r['L2_Population']:>12,}  "
        f"{r['L3_Population']:>12,}"
    )
